delete notification from id added
moira-alert/worker pull request #48
Opened 2017-04-21 11:44 UTC by melnikk

2017-04-29 04:52 UTC, beevee commented on moira/api/resources/notification.py
> +            result.append(jsonstr)
I don't understand this.

2017-05-02 04:26 UTC, melnikk commented on moira/api/resources/notification.py
> +            result.append(jsonstr)
Perhaps there was tricky bug with generators. But i do not remember unfortunately.

2017-05-02 05:26 UTC, beevee requested changes

2017-05-02 05:26 UTC, beevee commented on moira/api/resources/notification.py
> +            result.append(jsonstr)
If you use it as a way to convert generator to a list, you can just write `result = list(notifications)`. Or simply use `list(notifications)` in `self.write_json(request, {"list": list(notifications), "total": total})` and throw out unnecessary code.

2017-05-03 17:07 UTC, beevee approved these changes

2017-05-03 17:07 UTC, merged